/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a test_adap mainwindow.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "test_adap.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MainWindowAdaptor
 */

MainWindowAdaptor::MainWindowAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MainWindowAdaptor::~MainWindowAdaptor()
{
    // destructor
}

int MainWindowAdaptor::test()
{
    // handle method call local.MainWindow.test
    int out0;
    QMetaObject::invokeMethod(parent(), "test", Q_RETURN_ARG(int, out0));
    return out0;
}

int MainWindowAdaptor::test(const QString &str)
{
    // handle method call local.MainWindow.test
    int out0;
    QMetaObject::invokeMethod(parent(), "test", Q_RETURN_ARG(int, out0), Q_ARG(QString, str));
    return out0;
}

