/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p test_interface mainwindow.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef TEST_INTERFACE_H_1496229253
#define TEST_INTERFACE_H_1496229253

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface local.MainWindow
 */
class LocalMainWindowInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "local.MainWindow"; }

public:
    LocalMainWindowInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~LocalMainWindowInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<int> test()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("test"), argumentList);
    }

    inline QDBusPendingReply<int> test(const QString &str)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(str);
        return asyncCallWithArgumentList(QStringLiteral("test"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace local {
  typedef ::LocalMainWindowInterface MainWindow;
}
#endif
